
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jan 13 02:05:04 CET 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 18;
  public static final int READ = 12;
  public static final int PLUS = 14;
  public static final int INT = 5;
  public static final int SEMI = 22;
  public static final int CHAR = 6;
  public static final int LEFTPAR = 19;
  public static final int END = 4;
  public static final int INTCONST = 25;
  public static final int RIGHTPAR = 20;
  public static final int ID = 24;
  public static final int WRITE = 13;
  public static final int PROGRAM = 2;
  public static final int DOWNTO = 11;
  public static final int BEGIN = 3;
  public static final int COMMA = 23;
  public static final int EOF = 0;
  public static final int BY = 10;
  public static final int REALCONST = 27;
  public static final int CHARCONST = 26;
  public static final int DIV = 17;
  public static final int MINUS = 15;
  public static final int error = 1;
  public static final int ASSIGN = 21;
  public static final int FOR = 8;
  public static final int REAL = 7;
  public static final int MUL = 16;
  public static final int TO = 9;
}

